name: CI Build Configuration and Test Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install numpy
        pip install opencv-python
        pip install tensorflow
        pip install scikit-learn
        pip install scikit-image
    - name: Install virtual display
      run: sudo apt-get install -y xvfb      
    - name: Run skyscrapers solver with timeout
      run: |
        xvfb-run -a python main.py skyscrapers 8
        continue-on-error: true
     #   timeout 300s xvfb-run -a python main.py skyscrapers 8 > output.log 2>&1
     #   if grep -q "Error" output.log; then
     #     echo "Error found in skyscrapers solver' output, skipping subsequent steps"
     #     exit 1
     #   fi
      
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
